### ISSUE TITLE
ERROR! the role 'gengxiankun.docker-registry' was not found

### ISSUE THREAD

**Issue by patsevanton** [gengxiankun-galaxy/docker-registry#2]
ansible-galaxy install gengxiankun.docker_registry
- downloading role 'docker_registry', owned by gengxiankun
- downloading role from https://github.com/gengxiankun-galaxy/docker-registry/archive/master.tar.gz
- extracting gengxiankun.docker_registry to /home/user/.ansible/roles/gengxiankun.docker_registry
- gengxiankun.docker_registry (master) was installed successfully

**Comment by gengxiankun** [comment]
Has been installed successfully.
